# Generated by Django 5.2.8 on 2025-11-14 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_survey'),
        ('user_app', '0004_alter_customuser_email_alter_customuser_username'),
    ]

    operations = [
    ]
