# Generated by Django 5.2.8 on 2025-11-17 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_drop_allauth_tables'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chatmessage',
            table='chat_message',
        ),
        migrations.AlterModelTable(
            name='chatsession',
            table='chat_session',
        ),
    ]
