# Generated by Django 5.2.8 on 2025-11-17 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_alter_chatmessage_table_alter_chatsession_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='role',
            field=models.CharField(choices=[('user', '사용자'), ('assistant', '어시스턴트'), ('system', '상담 요약')], max_length=20),
        ),
    ]
