# Generated by Django 5.2.8 on 2025-11-14 01:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_app', '0005_merge_20251114_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='survey', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('M', '남성'), ('F', '여성'), ('O', '기타')], max_length=1)),
                ('is_pregnant', models.BooleanField(default=False)),
                ('preexisting_conditions', models.TextField(blank=True, null=True, verbose_name='지병')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='주소')),
            ],
        ),
    ]
