# Generated by Django 5.2.8 on 2025-11-17 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_table_and_pregnancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresponse',
            name='gender',
            field=models.CharField(choices=[('M', '남성'), ('F', '여성')], max_length=1),
        ),
    ]
